config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'first_first', to: 'pages#first_first', as: :first_first
  get 'first_second', to: 'pages#first_second', as: :first_second
  get 'explode', to: 'pages#explode', as: :explode
  get 'manual_release', to: 'pages#manual_release', as: :manual_release
  get 'space_jump', to: 'pages#space_jump', as: :space_jump
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home; end

  def first_first; end

  def first_second; end

  def explode; end

  def manual_release; end

  def space_jump; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/banner' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="anime.min.js"></script>
  </body>
</html>

app/views/pages/explode.html.erb
<div class="container">
  <div class="banner-content">
    <div class="front-img-cont cont_explode">
      <%= image_tag 'explode.jpg', class: "front-img_home" %>
    </div>
    <div class="decision-panel decision-panel_right">
      <div class="decision-panel_text">
        <h1>THE SHUTTLE EXPLODES!</h1>
        <p>And you with it. Try again?</p>
      </div>
      <div class="buttons">
        <%= link_to 'Restart', root_path, class: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/first_first.html.erb
<div class="container">
  <div class="banner-content">
    <div class="decision-panel decision-panel_left">
      <div class="decision-panel_text">
        <h1>THE RELEASE DOESN'T WORK!</h1>
        <p>You are racing back towards Earth. What do you do?</p>
      </div>
      <div class="buttons">
        <%= link_to 'Go out and try to fix it manually', manual_release_path, class: "button" %>
        <%= link_to 'Keep on pressing the release button', explode_path, class: "button" %>
      </div>
    </div>
    <div class="front-img-cont cont_first_first">
      <%= image_tag 'first_first.jpg', class: "front-img_home" %>
    </div>
  </div>
</div>

app/views/pages/first_second.html.erb
<div class="container">
  <div class="banner-content">
    <div class="decision-panel decision-panel_left">
      <div class="decision-panel_text">
        <h1>HOUSTON IS TRYING TO REACH YOU!</h1>
        <p>The connection is bad and it is hard to hear what they are saying. What do you do?</p>
      </div>
      <div class="buttons">
        <%= link_to 'Press the release button', first_first_path, class: "button" %>
        <%= link_to 'Try and improve the connection', explode_path, class: "button" %>
      </div>
    </div>
    <div class="front-img-cont cont_first_second">
      <%= image_tag 'first_second.jpg', class: "front-img_first_second" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="banner-content">
    <div class="front-img-cont cont_home">
      <%= image_tag 'space_home.jpg', class: "front-img_home" %>
    </div>
    <div class="decision-panel decision-panel_right">
      <div class="decision-panel_text">
        <h1>BOOSTER MALFUNCTION!</h1>
        <p>The main booster is forcing you off your flight path. What do you do?</p>
      </div>
      <div class="buttons">
        <%= link_to 'Release the booster', first_first_path, class: "button" %>
        <%= link_to 'Wait it out', first_second_path, class: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/manual_release.html.erb
<div class="container">
  <div class="banner-content">
    <div class="front-img-cont cont_manual_release">
      <%= image_tag 'manual_release.jpg', class: "front-img_home" %>
    </div>
    <div class="decision-panel decision-panel_right">
      <div class="decision-panel_text">
        <h1>IT IS TOO TOUGH!</h1>
        <p>The release doesn't budge. What do you do?</p>
      </div>
      <div class="buttons">
        <%= link_to 'Cut your safety line and jump away', space_jump_path, class: "button" %>
        <%= link_to 'Try and burn through the release', explode_path, class: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/space_jump.html.erb
<div class="container">
  <div class="banner-content">
    <div class="decision-panel decision-panel_left">
      <div class="decision-panel_text">
        <h1>OXYGEN LEVELS ARE LOW!</h1>
        <p>You are racing back towards Earth. What do you do?</p>
      </div>
      <div class="buttons">
        <%= link_to 'Go out and try to fix it manually', manual_release_path, class: "button" %>
        <%= link_to 'Keep on pressing the release button', explode_path, class: "button" %>
      </div>
    </div>
    <div class="front-img-cont cont_space_jump">
      <%= image_tag 'space_jump.jpg', class: "front-img_home" %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url('<%= image_path 'space.jpeg' %>');">

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>